version: "3.8"

services:
  db:
    container_name: db
    image: mysql:8.2.0-oracle
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}

  app:
    container_name: app
    build: ./
    ports:
      - "8080:80"
    depends_on:
      - db

  